const questions = [
  {
    id: 1,
    question: "What is the capital of India?",
    options: ["Delhi", "Mumbai", "Kolkata", "Chennai"],
    type: "one",
  },
  {
    id: 2,
    question:
      "Which of the following is the largest planet in our solar system?",
    options: ["Jupiter", "Venus", "Saturn", "Mars"],
    type: "one",
  },
  {
    id: 3,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "NaCl"],
    type: "one",
  },
  {
    id: 4,
    question: "Which of the following is not a primary color?",
    options: ["Red", "Green", "Blue", "Yellow"],
    type: "one",
  },
  {
    id: 5,
    question: "Which of the following are mammal animals?",
    options: ["Lion", "Crocodile", "Elephant", "Eagle"],
    type: "many",
  },
  {
    id: 6,
    question: "Which of the following are programming languages?",
    options: ["Java", "HTML", "CSS", "Python"],
    type: "many",
  },
  {
    id: 7,
    question: "Which of the following are European countries?",
    options: ["Brazil", "Italy", "India", "Japan"],
    type: "many",
  },
  {
    id: 8,
    question: "Which planet is known as the 'Red Planet'?",
    options: ["Mars", "Neptune", "Jupiter", "Saturn"],
    type: "one",
  },
  {
    id: 9,
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Arctic Ocean",
      "Indian Ocean",
      "Pacific Ocean",
    ],
    type: "one",
  },
  {
    id: 10,
    question: "Which of the following are programming languages?",
    options: ["Ruby", "Swift", "Perl", "C++"],
    type: "many",
  },
  {
    id: 11,
    question: "Who wrote the play 'Romeo and Juliet'?",
    options: [
      "William Shakespeare",
      "Charles Dickens",
      "Mark Twain",
      "Jane Austen",
    ],
    type: "one",
  },
  {
    id: 12,
    question:
      "Which gas do plants absorb from the atmosphere to perform photosynthesis?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    type: "one",
  },
  {
    id: 13,
    question: "Which of the following is a primary color?",
    options: ["Purple", "Green", "Yellow", "Orange"],
    type: "one",
  },
  {
    id: 14,
    question: "Which of the following are famous inventors?",
    options: [
      "Thomas Edison",
      "Alexander Graham Bell",
      "Marie Curie",
      "Isaac Newton",
    ],
    type: "many",
  },
  {
    id: 15,
    question: "What is the tallest mountain in the world?",
    options: [
      "Mount Kilimanjaro",
      "Mount Everest",
      "Mount McKinley",
      "Mount Fuji",
    ],
    type: "one",
  },
  {
    id: 16,
    question: "Which of the following are programming languages?",
    options: ["JavaScript", "SQL", "Ruby", "HTML"],
    type: "many",
  },
  {
    id: 17,
    question: "What is the largest organ in the human body?",
    options: ["Liver", "Heart", "Skin", "Lung"],
    type: "one",
  },
  {
    id: 18,
    question: "Which of the following are countries in South America?",
    options: ["Argentina", "Thailand", "Egypt", "Brazil"],
    type: "many",
  },
  {
    id: 19,
    question: "Who is known as the 'Father of Modern Physics'?",
    options: [
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Nikola Tesla",
    ],
    type: "one",
  },
  {
    id: 20,
    question: "Which of the following are famous art movements?",
    options: [
      "Renaissance",
      "Abstract Expressionism",
      "Cubism",
      "Impressionism",
    ],
    type: "many",
  },
  {
    id: 21,
    question: "Which planet is known as the 'Morning Star' or 'Evening Star'?",
    options: ["Venus", "Mercury", "Mars", "Saturn"],
    type: "one",
  },
  {
    id: 22,
    question: "Who is the author of the famous novel 'Pride and Prejudice'?",
    options: [
      "Jane Austen",
      "Charlotte Bronte",
      "George Orwell",
      "Leo Tolstoy",
    ],
    type: "one",
  },
  {
    id: 23,
    question: "Which of the following are elements in the periodic table?",
    options: ["Carbon", "Water", "Gold", "Helium"],
    type: "many",
  },
  {
    id: 24,
    question: "What is the currency of Japan?",
    options: ["Yen", "Dollar", "Euro", "Pound"],
    type: "one",
  },
  {
    id: 25,
    question: "Which of the following are famous Greek philosophers?",
    options: ["Socrates", "Aristotle", "Confucius", "Plato"],
    type: "many",
  },
  {
    id: 26,
    question: "What is the largest mammal on Earth?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    type: "one",
  },
  {
    id: 27,
    question: "Which of the following are programming languages?",
    options: ["Python", "Fruit", "C#", "Java"],
    type: "many",
  },
  {
    id: 28,
    question: "What is the capital of Brazil?",
    options: ["São Paulo", "Rio de Janeiro", "Brasília", "Buenos Aires"],
    type: "one",
  },
  {
    id: 29,
    question: "Which of the following are noble gases?",
    options: ["Helium", "Oxygen", "Nitrogen", "Argon"],
    type: "many",
  },
  {
    id: 30,
    question: "Who painted the famous artwork 'Mona Lisa'?",
    options: [
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Salvador Dalí",
    ],
    type: "one",
  },
  {
    id: 31,
    question: "Which gas is responsible for the green color of leaves?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Chlorophyll"],
    type: "one",
  },
  {
    id: 32,
    question: "Who wrote the famous play 'Hamlet'?",
    options: [
      "Christopher Marlowe",
      "William Shakespeare",
      "John Milton",
      "George Bernard Shaw",
    ],
    type: "one",
  },
  {
    id: 33,
    question: "Which of the following are programming languages?",
    options: ["CSS", "German", "Swift", "SQL"],
    type: "many",
  },
  {
    id: 34,
    question: "What is the chemical symbol for the element Iron?",
    options: ["Fe", "I", "In", "Ir"],
    type: "one",
  },
  {
    id: 35,
    question: "Which of the following are oceans?",
    options: [
      "Indian Ocean",
      "Mediterranean Sea",
      "Atlantic Ocean",
      "Black Sea",
    ],
    type: "many",
  },
  {
    id: 36,
    question: "What is the largest bird in the world?",
    options: ["Penguin", "Ostrich", "Eagle", "Albatross"],
    type: "one",
  },
  {
    id: 37,
    question: "Which of the following are European capitals?",
    options: ["Berlin", "Beijing", "Rome", "New Delhi"],
    type: "many",
  },
  {
    id: 38,
    question: "Which planet is known as the 'Blue Planet'?",
    options: ["Venus", "Neptune", "Earth", "Uranus"],
    type: "one",
  },
  {
    id: 39,
    question: "Who is the author of the 'Harry Potter' book series?",
    options: [
      "J.R.R. Tolkien",
      "J.K. Rowling",
      "C.S. Lewis",
      "George R.R. Martin",
    ],
    type: "one",
  },
  {
    id: 40,
    question: "Which of the following are famous scientists?",
    options: [
      "Albert Einstein",
      "Stephen King",
      "Marie Curie",
      "Vincent van Gogh",
    ],
    type: "many",
  },
  {
    id: 41,
    question: "What is the currency of the United Kingdom?",
    options: ["Pound Sterling", "Euro", "Dollar", "Yen"],
    type: "one",
  },
  {
    id: 42,
    question:
      "Which of the following are natural satellites (moons) in our solar system?",
    options: ["Ganymede", "Titan", "Pluto", "Mars"],
    type: "many",
  },
  {
    id: 43,
    question: "What is the largest organ in the human body?",
    options: ["Liver", "Heart", "Skin", "Brain"],
    type: "one",
  },
  {
    id: 44,
    question: "Which of the following are South American countries?",
    options: ["Mexico", "Peru", "Egypt", "Japan"],
    type: "many",
  },
  {
    id: 45,
    question: "What is the chemical symbol for the element Gold?",
    options: ["Au", "Ag", "Go", "Gd"],
    type: "one",
  },
  {
    id: 46,
    question: "Which of the following are programming languages?",
    options: ["CSS", "SQL", "Russian", "JavaScript"],
    type: "many",
  },
  {
    id: 47,
    question: "What is the capital of Australia?",
    options: ["Sydney", "Canberra", "Melbourne", "Brisbane"],
    type: "one",
  },
  {
    id: 48,
    question: "Which of the following are noble gases?",
    options: ["Helium", "Oxygen", "Carbon Dioxide", "Xenon"],
    type: "many",
  },
  {
    id: 49,
    question: "Who painted the famous artwork 'The Starry Night'?",
    options: [
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Claude Monet",
    ],
    type: "one",
  },
  {
    id: 50,
    question: "What is the largest mammal in the ocean?",
    options: ["Killer Whale", "Blue Whale", "Dolphin", "Sperm Whale"],
    type: "one",
  },
];

export { questions };
